'use client';
/* Hallmark · Index-First · modern-minimal · existing purple/gold tokens · P5 H5 E4 S5 R5 V4 */
import { useEffect, useId, useState } from 'react';
import Link from 'next/link';
import { adminFetch } from '@/frontend/lib/admin-upload';
import Image from 'next/image';
import { teamPosters } from '@/shared/data/team-posters';
import { recapStoriesData } from '@/shared/data/homepage-data';
import './website-workspace.css';

type Stat={label:string;value:string;subtext?:string;icon?:string};
type Journey={phase:string;title:string;date:string;description:string;highlight:string};
type Section={id:string;key:string;title:string;description:string;enabled:boolean;sort_order:number;asset_id:string|null;content:{stats?:Stat[];journey?:Journey[]}};
type Asset={id:string;url:string;filename:string;alt:string};
type Settings=Record<string,unknown>;
type FieldHelp={purpose:string;format:string;example:string;max:number};
const fieldHelp:Record<string,FieldHelp>={
  'Tên số liệu':{purpose:'Nhãn dưới con số trên trang chủ; giúp người xem biết số liệu đang nói về điều gì.',format:'Bắt buộc. Viết tên chỉ số ngắn, không nhập con số vào đây.',example:'Phần quà Trung Thu',max:160},
  'Giá trị':{purpose:'Con số nổi bật của chỉ số này. Để trống thì chỉ số không xuất hiện trên website.',format:'Văn bản ngắn; có thể dùng số, dấu + hoặc đơn vị. Chỉ nhập kết quả đã xác nhận.',example:'65 hoặc 65 phần quà',max:80},
  'Tên giai đoạn':{purpose:'Nhãn của chặng, hiển thị cạnh thời gian và số thứ tự.',format:'Bắt buộc. Nên dùng 2–4 từ; không cần tự đánh số chặng.',example:'Chuẩn bị',max:160},
  'Tiêu đề chặng':{purpose:'Tên nổi bật của câu chuyện trong chặng này.',format:'Bắt buộc. Một câu ngắn, khác với tên giai đoạn.',example:'Gói ghém một mùa trăng',max:160},
  'Thời gian':{purpose:'Mốc thời gian xuất hiện cạnh tên giai đoạn.',format:'Không bắt buộc; nhập chữ hoặc ngày DD/MM/YYYY. Không tự chuyển định dạng ngày.',example:'27/09/2026 hoặc Tháng 9/2026',max:80},
  'Câu chuyện':{purpose:'Kể những hoạt động và điều đáng nhớ của chặng.',format:'Nhấn Enter để xuống dòng; nhấn Enter hai lần để tách đoạn có khoảng cách trên trang chủ. Văn bản thường, không hỗ trợ HTML/Markdown. Nên viết 2–4 câu mỗi đoạn.',example:'Các thành viên cùng chuẩn bị và đóng gói những phần quà gửi đến các em.',max:2000},
  'Điểm nhấn':{purpose:'Câu được nhấn mạnh sau phần câu chuyện của chặng.',format:'Không bắt buộc. Nên dùng một câu; không cần thêm dấu ** để in đậm.',example:'Phía sau đêm hội là tâm sức của cả tập thể.',max:1000},
  'Dòng chữ phía trên tên chương trình':{purpose:'Dòng dẫn nhỏ ở phần mở đầu trang chủ.',format:'Văn bản ngắn; có thể dùng dấu · để ngăn hai ý.',example:'MỘT MÙA TRĂNG · MỘT HÀNH TRÌNH',max:200},
  'Nút đến cây kỷ niệm':{purpose:'Chữ trên nút dẫn đến trang cây kỷ niệm. Đường dẫn đã được hệ thống thiết lập.',format:'Chỉ nhập tên nút, không nhập URL. Để trống sẽ dùng tên mặc định.',example:'Đến cây kỷ niệm',max:160},
  'Nút xem dấu ấn chương trình':{purpose:'Chữ trên nút cuộn đến khu vực dấu ấn trên trang chủ.',format:'Chỉ nhập tên nút, không nhập URL. Để trống sẽ dùng tên mặc định.',example:'Xem dấu ấn chương trình',max:160},
  'Tên ở dòng bản quyền':{purpose:'Tên chương trình xuất hiện sau năm ở dòng bản quyền cuối trang.',format:'Bắt buộc. Chỉ nhập tên; hệ thống tự thêm ký hiệu © và năm.',example:'Vầng Trăng Hòa Sắc 2',max:200},
  'Lời cảm ơn':{purpose:'Đoạn lời cảm ơn ở chân trang, phía dưới câu kết nổi bật.',format:'Văn bản thường, không hỗ trợ HTML/Markdown. Nên viết 2–3 câu.',example:'Cảm ơn từng tình nguyện viên và người đồng hành đã góp nên mùa trăng này.',max:2000},
  'Câu kết nổi bật':{purpose:'Tiêu đề lớn của phần chân trang.',format:'Một câu ngắn bằng văn bản thường; không cần chèn thẻ HTML.',example:'Trăng rồi sẽ khuyết. Điều thương còn đầy.',max:2000},
  'Tên trang':{purpose:'Tiêu đề trên trang cây kỷ niệm, độc lập với tên chương trình trên trang chủ.',format:'Bắt buộc. Nên dùng tên ngắn, dễ nhận biết.',example:'Cây kỷ niệm',max:160},
  'Dòng dẫn':{purpose:'Dòng chữ giới thiệu ngắn trên trang cây kỷ niệm.',format:'Văn bản thường, một câu ngắn.',example:'Một mùa trăng · Ngàn điều muốn nói',max:200},
  'Giới thiệu':{purpose:'Giải thích cho người xem cách gửi và lưu giữ lời nhắn trên cây kỷ niệm.',format:'Văn bản thường; không hỗ trợ HTML/Markdown. Nên viết 2–3 câu.',example:'Cùng treo những kỷ niệm và lời nhắn của bạn lên cây mùa trăng.',max:2000},
  'Tiêu đề hướng dẫn':{purpose:'Tiêu đề khu vực hướng dẫn trên trang Cây kỷ niệm.',format:'Bắt buộc. Viết một câu ngắn bằng văn bản thường.',example:'Gửi một lời nhắn, giữ một mùa trăng',max:160},
  'Hướng dẫn gửi lời nhắn':{purpose:'Giúp khách hiểu cách viết và đọc lời nhắn trước khi đến cây.',format:'Văn bản thường. Enter để xuống dòng; nên viết 2–3 câu.',example:'Chọn lồng đèn hoặc ngôi sao, viết lời nhắn rồi gửi lên cây.',max:2000},
  'Lời kết trang Cây kỷ niệm':{purpose:'Lời cảm ơn xuất hiện cuối trang /memories.',format:'Văn bản thường. Enter để xuống dòng; để trống để không hiển thị lời kết.',example:'Cảm ơn bạn đã góp nên mùa trăng này.',max:2000},
};
function WebsiteField({label,value,onChange,textarea,required,help}:{label:string;value:string;onChange:(v:string)=>void;textarea:boolean;required:boolean;help:FieldHelp}){
  const id=useId();
  return <div className="website-field"><label htmlFor={id}>{label}{required&&' *'}</label>{textarea?<textarea id={id} rows={4} required={required} className="admin-control" maxLength={help.max} value={value} aria-describedby={`${id}-help`} placeholder={help.example} onChange={e=>onChange(e.target.value)}/>:<input id={id} className="admin-control" required={required} maxLength={help.max} value={value} aria-describedby={`${id}-help`} placeholder={help.example} onChange={e=>onChange(e.target.value)}/>}<div id={`${id}-help`} className="website-field-help"><p>{help.purpose}</p><p>{help.format} Tối đa {help.max.toLocaleString('vi-VN')} ký tự.</p><p>Ví dụ: {help.example}</p><span>{value.length}/{help.max}</span></div></div>;
}
function visibleSections(sections:Section[],settings:Settings){
  const defaults:Record<string,{title:string;description:string}>={
    hero:{title:String(settings.heroTitle??''),description:String(settings.heroDescription??'')},
    volunteers:{title:'Thẻ tình nguyện viên',description:'Mỗi chiếc thẻ lưu giữ một gương mặt đã cùng góp sức cho mùa trăng.'},
    recap:{title:'Dấu ấn mùa trăng',description:'Từ những ngày chuẩn bị đến đêm hội rước đèn, mỗi chặng đường đều có dấu tay của những người cùng góp sức.'},
    footer:{title:String(settings.heroTitle??''),description:'Cảm ơn từng tình nguyện viên, người đồng hành và những tấm lòng đã góp nên Vầng Trăng Hòa Sắc 2. Nếu có một kỷ niệm muốn giữ lại, hãy gửi lời nhắn lên cây mùa trăng của chúng mình.'},
  };
  return sections.map(s=>({...s,title:s.title||defaults[s.key]?.title||'',description:s.description||defaults[s.key]?.description||''}));
}
const pages:Record<string,{title:string;description:string;keys:string[]}>= {
  hero:{title:'Mở đầu trang chủ',description:'Tên chương trình, lời giới thiệu và hai nút điều hướng đầu trang.',keys:['hero']},
  team:{title:'Poster đội ngũ',description:'Ban tổ chức, ban cố vấn và các ban cùng xuất hiện trong một slideshow.',keys:['organizers','advisors','departments']},
  volunteers:{title:'Thẻ tình nguyện viên',description:'Chỉnh tiêu đề và lời dẫn phía trên bộ thẻ. Upload và phân ban ở mục Tình nguyện viên.',keys:['volunteers']},
  recap:{title:'Dấu ấn & hành trình',description:'Số liệu cho biết kết quả, các chặng kể lại cách chương trình diễn ra. Chúng cùng xuất hiện trong khu vực Dấu ấn trên trang chủ nên được chỉnh tại đây.',keys:['recap']},
  footer:{title:'Chân trang',description:'Lời cảm ơn và thông tin cuối trang chủ.',keys:['footer']},
  brand:{title:'Logo & ảnh nền',description:'Hình ảnh nhận diện dùng trên toàn bộ website. Ảnh upload giữ chất lượng gốc.',keys:[]},
  memories:{title:'Trang Cây kỷ niệm',description:'Quản lý landing page /memories: lời mở đầu, hướng dẫn gửi lời nhắn và lời kết. Cây và các lời nhắn luôn được giữ nguyên.',keys:[]},
};
const statFields=['statPresents','statScholarships','statVolunteers','statLanterns'];
async function api(url:string,init?:RequestInit){let r=await adminFetch(url,init);if(r.status===401){const refresh=await fetch('/api/admin/auth',{method:'PATCH'});if(refresh.ok)r=await adminFetch(url,init);}const d=await r.json();if(!r.ok)throw new Error(d.error||'Không thể tải hoặc lưu cấu hình.');return d;}
async function assetsList(){const result:Asset[]=[];let offset:number|null=0;while(offset!==null){const d=await api(`/api/admin/assets?limit=100&offset=${offset}`);result.push(...d.items);offset=d.next_offset;}return result;}

export function WebsiteWorkspace({view,onBusyChange,onDirtyChange}:{view:string;onBusyChange:(v:boolean)=>void;onDirtyChange:(v:boolean)=>void}){
  const helpPrefix=useId();
  const [sections,setSections]=useState<Section[]>([]),[settings,setSettings]=useState<Settings>({}),[assets,setAssets]=useState<Asset[]>([]);
  const [activeJourney,setActiveJourney]=useState<number|null>(0);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0);
  useEffect(()=>{onBusyChange(busy);return()=>onBusyChange(false);},[busy,onBusyChange]);
  useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
  useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
  useEffect(()=>{let active=true;Promise.all([api('/api/admin/website'),['team','brand'].includes(view)?assetsList():Promise.resolve([])]).then(([d,a])=>{if(active){setSections(visibleSections(d.sections,d.settings));setSettings({...d.settings,primaryButton:d.settings.primaryButton||'Đến cây kỷ niệm',secondaryButton:d.settings.secondaryButton||'Xem dấu ấn chương trình'});setAssets(a);setDirty(false);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[revision,view]);
  function change(){setDirty(true);setNotice('');setError('');}
  function setting(key:string,value:unknown){change();setSettings(old=>({...old,[key]:value}));}
  function section(key:string,patch:Partial<Section>){change();setSections(old=>old.map(s=>s.key===key?{...s,...patch}:s));}
  function leave(e:React.MouseEvent<HTMLAnchorElement>){if(busy||(dirty&&!confirm('Rời trang và bỏ các thay đổi chưa lưu?')))e.preventDefault();}
  const current=sections.find(s=>s.key===pages[view]?.keys[0]);
  const recap=sections.find(s=>s.key==='recap');
  const stats=recap?.content?.stats??['Phần quà Trung Thu','Học bổng vượt khó','Chiến sĩ tình nguyện','Lồng đèn thắp sáng'].map((label,i)=>({label,value:String(settings[statFields[i]]??'')}));
  const journey=recap?.content?.journey??recapStoriesData;
  function recapContent(patch:Partial<Section['content']>){if(recap)section('recap',{content:{...recap.content,...patch}});}
  const blocks=Object.entries(pages).filter(([,p])=>p.keys.length).map(([key,p])=>({key,...p,items:sections.filter(s=>p.keys.includes(s.key)).sort((a,b)=>a.sort_order-b.sort_order)})).sort((a,b)=>Math.min(...a.items.map(s=>s.sort_order))-Math.min(...b.items.map(s=>s.sort_order)));
  function move(index:number,delta:number){const next=[...blocks];[next[index],next[index+delta]]=[next[index+delta],next[index]];const order=next.flatMap(b=>b.items.map(s=>s.id));change();setSections(old=>old.map(s=>({...s,sort_order:order.indexOf(s.id)})));}
  async function save(){
    setBusy(true);setError('');setNotice('');
    const keys=pages[view]?.keys??[];
    const settingsKeys:Record<string,string[]>={hero:['heroTitle','heroSubtitle','heroDescription','primaryButton','secondaryButton'],footer:['footerQuote'],brand:['logo_asset_id','background_asset_id'],memories:['memoriesTitle','memoriesSubtitle','memoriesDescription','memoriesIntroVisible','memoriesGuideVisible','memoriesFooterVisible','memoriesGuideTitle','memoriesGuideDescription','memoriesFooterText']};
    let patches:Partial<Section>[]=[];
    if(view==='overview')patches=sections.map(({id,enabled,sort_order})=>({id,enabled,sort_order}));
    else patches=sections.filter(s=>keys.includes(s.key)).map(s=>({id:s.id,title:s.title,description:s.description,enabled:s.enabled,...(view==='team'?{asset_id:s.asset_id}:{}),...(view==='recap'?{content:{stats,journey}}:{})}));
    const settingPatch=Object.fromEntries((settingsKeys[view]??[]).map(k=>[k,settings[k]??(k.endsWith('_asset_id')?null:'')]));
    if(view==='hero'&&current){settingPatch.heroTitle=current.title;settingPatch.heroDescription=current.description;}
    try{await api('/api/admin/website',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...(Object.keys(settingPatch).length?{settings:settingPatch}:{}),...(patches.length?{sections:patches}:{})})});setDirty(false);setNotice('Đã lưu. Nội dung mới đã được cập nhật trên website.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  function field(label:string,value:string,onChange:(v:string)=>void,textarea=false,required=false){
    const help=fieldHelp[label]??(label==='Tiêu đề'?{purpose:view==='hero'?'Tên chương trình ở phần mở đầu; cũng đồng bộ với tên nhận diện.':`Tiêu đề của khu vực ${pages[view]?.title??''} trên trang chủ.`,format:'Bắt buộc. Văn bản thường; nên viết ngắn, không dùng HTML/Markdown.',example:view==='hero'?'Vầng Trăng Hòa Sắc 2':view==='volunteers'?'Thẻ tình nguyện viên':'Dấu ấn mùa trăng',max:view==='hero'?160:200}:{purpose:`Đoạn dẫn phía dưới tiêu đề khu vực ${pages[view]?.title??''}.`,format:'Văn bản thường; không hỗ trợ HTML/Markdown. Nên viết 1–3 câu.',example:'Từ những ngày chuẩn bị đến đêm hội, mỗi chặng đều có dấu tay của những người cùng góp sức.',max:2000});
    return <WebsiteField key={label} label={label} value={value} onChange={onChange} textarea={textarea} required={required} help={help}/>;
  }
  function sf(label:string,key:string,textarea=false){return field(label,String(settings[key]??''),v=>setting(key,v),textarea,key.endsWith('Title'));}
  function memoryToggle(label:string,key:string){return <><label className="website-toggle"><input type="checkbox" checked={settings[key]!==false} aria-describedby={`${key}-help`} onChange={e=>setting(key,e.target.checked)}/>{label}</label><p className="website-field-help" id={`${key}-help`}>Bỏ tick chỉ ẩn khu vực này sau khi lưu, không xóa nội dung hoặc lời nhắn trên cây.</p></>;}
  async function upload(file:File|undefined,onSelect:(id:string)=>void){if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.set('file',file);const d=await api('/api/admin/upload',{method:'POST',body:form});setAssets(old=>[d.asset,...old]);onSelect(d.asset.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function media(label:string,id:string|null,onSelect:(id:string|null)=>void,fallback?:string,scope=label){
    const asset=assets.find(a=>a.id===id),hintId=`${helpPrefix}-${scope.replace(/\s+/g,'-')}`;
    return <div className="website-media"><h3>{label}</h3>{(asset||fallback)&&<Image src={asset?.url||fallback!} alt={asset?.alt||label} width={1200} height={800} unoptimized className="website-media-image"/>}<label className="website-field">Ảnh trong thư viện<select className="admin-control" value={id??''} aria-describedby={`${hintId}-select`} onChange={e=>onSelect(e.target.value||null)}><option value="">Dùng ảnh mặc định</option>{assets.map(a=><option key={a.id} value={a.id}>{a.filename}</option>)}</select></label><p id={`${hintId}-select`} className="website-field-help">Chọn một ảnh đã upload; không cần dán đường dẫn. “Dùng ảnh mặc định” khôi phục ảnh hoặc bộ poster có sẵn sau khi lưu.</p><label className="website-upload">Upload ảnh mới<input type="file" accept="image/jpeg,image/png,image/webp" aria-describedby={`${hintId}-upload`} onChange={e=>{void upload(e.target.files?.[0],id=>onSelect(id));e.target.value='';}}/></label><div id={`${hintId}-upload`} className="website-field-help"><p>Chọn một tệp JPEG, PNG hoặc WebP, tối đa 10 MB. Giữ nguyên chất lượng gốc; ảnh vừa upload được chọn vào trường này, cần bấm “Lưu thay đổi” để áp dụng.</p><p>{label==='Logo chương trình'?'Nên dùng PNG nền trong suốt, nội dung logo nằm giữa ảnh.':label==='Ảnh nền website'?'Nên dùng ảnh ngang độ phân giải cao. Ảnh nền phủ màn hình nên phần sát mép có thể nằm ngoài khung ở các thiết bị khác nhau.':'Dùng poster hoàn chỉnh, có sẵn tên và thông tin đội ngũ. Ảnh sẽ được hiển thị đầy đủ theo tỷ lệ gốc.'}</p></div></div>;
  }
  if(loading)return <p className="admin-empty" role="status">Đang tải cấu hình website…</p>;
  if(!sections.length)return <div className="admin-notice" role="alert">{error||'Chưa có cấu hình trang chủ.'}<button className="admin-secondary" onClick={()=>{setLoading(true);setRevision(n=>n+1);}}>Thử tải lại</button></div>;
  const page=pages[view];
  return <section className="website-workspace">
    {view!=='overview'&&<Link href="/admin/website" className="admin-text-button website-back" onClick={leave}>← Quản lý website</Link>}
    <header className="admin-page-heading"><div><span className="admin-kicker">Website / {view==='overview'?'Trang chủ':page?.title}</span><h1>{page?.title??'Quản lý trang chủ'}</h1><p>{page?.description??'Sắp xếp các khối hiển thị và mở đúng màn để chỉnh nội dung. Thay đổi chỉ áp dụng khi bạn bấm lưu.'}</p></div><Link href={view==='memories'?'/memories':'/'} target="_blank" className="admin-secondary">Xem website ↗</Link></header>
    {error&&<p className="admin-notice" role="alert">{error}</p>}{notice&&<p className="website-success" role="status">{notice}</p>}
    <p className="website-hint website-input-guide">Dấu * là trường bắt buộc. Nhập văn bản thường, không cần mã HTML hay Markdown. Thay đổi chỉ xuất hiện trên website sau khi bấm “Lưu thay đổi”.</p><form onSubmit={e=>{e.preventDefault();void save();}}>
    <fieldset disabled={busy} className="website-fields">
    {view==='overview'?<>
      <p id="layout-visibility-help" className="website-hint">Tick “Hiển thị” để bật cả khối; bỏ tick để ẩn và giữ lại nội dung. Với đội ngũ, lựa chọn này áp dụng cả ba nhóm poster. Nút ↑/↓ thay vị trí khối, không đổi thứ tự thành viên. Bấm lưu để áp dụng.</p><div className="website-list-head"><h2>Bố cục trang chủ</h2><span>Thứ tự từ trên xuống</span></div>
      <div className="website-index">{blocks.map((b,i)=><div key={b.key} className="website-index-row"><span className="website-index-number">{String(i+1).padStart(2,'0')}</span><div className="website-index-copy"><h3>{b.title}</h3><p>{b.description}</p>{!b.items.length&&<small>Chưa có cấu hình khu vực này.</small>}</div><div className="website-index-controls"><Link className="admin-secondary website-edit-link" href={`/admin/website/${b.key}`} onClick={leave} aria-label={`Chỉnh sửa ${b.title}`}>Chỉnh sửa</Link><label><input type="checkbox" disabled={!b.items.length} checked={b.items.some(s=>s.enabled)} aria-describedby="layout-visibility-help" onChange={e=>{change();setSections(old=>old.map(s=>b.keys.includes(s.key)?{...s,enabled:e.target.checked}:s));}}/>Hiển thị</label><div><button type="button" aria-label={`Đưa ${b.title} lên`} disabled={i===0} onClick={()=>move(i,-1)}>↑</button><button type="button" aria-label={`Đưa ${b.title} xuống`} disabled={i===blocks.length-1} onClick={()=>move(i,1)}>↓</button></div></div></div>)}</div>
      <div className="website-secondary-index"><Link href="/admin/website/brand" onClick={leave}><strong>Logo & ảnh nền</strong><span>Nhận diện chung cho website</span><b>Chỉnh sửa</b></Link><Link href="/admin/website/memories" onClick={leave}><strong>Trang Cây kỷ niệm</strong><span>Bố cục và nội dung tại /memories</span><b>Chỉnh sửa</b></Link></div>
    </>:<div className="website-editor-grid"><div className="website-editor-main">
      {current&&view!=='team'&&<section className="admin-panel website-form-panel"><h2>Nội dung hiển thị</h2><label className="website-toggle"><input type="checkbox" checked={current.enabled} aria-describedby="section-visibility-help" onChange={e=>section(current.key,{enabled:e.target.checked})}/>Hiển thị trên trang chủ</label><p id="section-visibility-help" className="website-field-help">Bật để hiển thị toàn bộ khu vực này trên trang chủ. Tắt chỉ ẩn khu vực; nội dung, số liệu và ảnh vẫn được giữ để bật lại. Cần lưu để áp dụng.</p>{field(view==='footer'?'Tên ở dòng bản quyền':'Tiêu đề',current.title,v=>section(current.key,{title:v}),false,true)}{field(view==='footer'?'Lời cảm ơn':'Lời giới thiệu',current.description,v=>section(current.key,{description:v}),true)}{view==='hero'&&<>{sf('Dòng chữ phía trên tên chương trình','heroSubtitle')}<div className="website-form-pair">{sf('Nút đến cây kỷ niệm','primaryButton')}{sf('Nút xem dấu ấn chương trình','secondaryButton')}</div></>}{view==='footer'&&sf('Câu kết nổi bật','footerQuote',true)}</section>}
      {view==='volunteers'&&<div className="website-related"><h2>Quản lý bộ thẻ</h2><p>Ảnh thẻ, ban và vai trò được quản lý cùng nhau ở màn Tình nguyện viên chương trình.</p><Link className="admin-secondary" href="/admin/volunteers" onClick={leave}>Mở bộ thẻ ↗</Link></div>}
      {view==='team'&&pages.team.keys.map(key=>{const s=sections.find(s=>s.key===key);const posters=teamPosters.filter(p=>p.section===key);return s&&<section className="admin-panel website-form-panel" key={key}><div className="website-group-heading"><h2>{key==='organizers'?'Ban tổ chức':key==='advisors'?'Ban cố vấn':'Các ban chuyên môn'}</h2><label className="website-toggle"><input type="checkbox" checked={s.enabled} aria-describedby={`group-${key}-help`} onChange={e=>section(key,{enabled:e.target.checked})}/>Hiển thị</label></div><p id={`group-${key}-help`} className="website-field-help">Bật/tắt riêng nhóm poster này trong slideshow. Tắt sẽ ẩn nhóm sau khi lưu, không xóa ảnh hoặc thẻ thành viên.</p><div className="website-posters">{!s.asset_id&&posters.map(p=><figure key={p.src}><Image src={p.src} alt={p.title} width={1063} height={650} unoptimized/><figcaption>{p.title}</figcaption></figure>)}</div>{media('Ảnh thay thế cho nhóm',s.asset_id,id=>section(key,{asset_id:id}),undefined,key)}<p className="website-hint">Để mặc định sẽ dùng bộ {posters.length} poster hiện có. Chọn hoặc upload ảnh để thay cả nhóm bằng một poster.</p></section>;})}
      {view==='brand'&&<section className="admin-panel website-form-panel"><h2>Hình ảnh nhận diện</h2><div className="website-form-pair">{media('Logo chương trình',settings.logo_asset_id as string|null,id=>setting('logo_asset_id',id),'/branding/Logo_VTHS.png')}{media('Ảnh nền website',settings.background_asset_id as string|null,id=>setting('background_asset_id',id),'/branding/background_khongten_logo.png')}</div></section>}
      {view==='memories'&&<><section className="admin-panel website-form-panel"><h2>01 · Mở đầu trang</h2>{memoryToggle('Hiển thị lời mở đầu','memoriesIntroVisible')}{sf('Tên trang','memoriesTitle')}{sf('Dòng dẫn','memoriesSubtitle')}{sf('Giới thiệu','memoriesDescription',true)}</section><section className="admin-panel website-form-panel"><h2>02 · Hướng dẫn gửi lời nhắn</h2>{memoryToggle('Hiển thị hướng dẫn','memoriesGuideVisible')}{sf('Tiêu đề hướng dẫn','memoriesGuideTitle')}{sf('Hướng dẫn gửi lời nhắn','memoriesGuideDescription',true)}<p className="website-hint">Hai nút “Gửi lời nhắn” và “Đọc lời nhắn” dẫn đến đúng khu vực có sẵn. Cây, biểu mẫu và danh sách lời nhắn luôn hoạt động.</p></section><section className="admin-panel website-form-panel"><h2>03 · Lời kết</h2>{memoryToggle('Hiển thị lời kết','memoriesFooterVisible')}{sf('Lời kết trang Cây kỷ niệm','memoriesFooterText',true)}</section><div className="website-related"><h2>Logo & ảnh nền</h2><p>Trang Cây kỷ niệm dùng chung nhận diện đã thiết lập cho website.</p><Link className="admin-secondary" href="/admin/website/brand" onClick={leave}>Chỉnh sửa nhận diện</Link></div></>}
      {view==='recap'&&<><section className="admin-panel website-form-panel"><div className="website-group-heading"><h2>Số liệu chương trình</h2><button className="admin-secondary" type="button" disabled={stats.length>=12} onClick={()=>recapContent({stats:[...stats,{label:'',value:''}]})}>Thêm số liệu</button></div><p className="website-hint">Dùng số liệu thực tế. Không muốn hiển thị số liệu nào thì gỡ mục đó.</p>{stats.map((s,i)=><div className="website-repeater" key={i}><div className="website-form-pair">{field('Tên số liệu',s.label,v=>recapContent({stats:stats.map((o,j)=>i===j?{...o,label:v}:o)}),false,true)}{field('Giá trị',s.value,v=>recapContent({stats:stats.map((o,j)=>i===j?{...o,value:v}:o)}))}</div><button className="admin-text-button" type="button" onClick={()=>recapContent({stats:stats.filter((_,j)=>j!==i)})}>Gỡ số liệu</button></div>)}</section>
      <section className="admin-panel website-form-panel"><div className="website-group-heading"><h2>Các chặng hành trình</h2><button className="admin-secondary" type="button" disabled={journey.length>=100} onClick={()=>{setActiveJourney(journey.length);recapContent({journey:[...journey,{phase:'',title:'',date:'',description:'',highlight:''}]});}}>Thêm chặng</button></div>{journey.map((s,i)=><details className="website-repeater website-journey" key={i} open={activeJourney===i} onInvalidCapture={()=>setActiveJourney(i)}><summary onClick={e=>{e.preventDefault();setActiveJourney(activeJourney===i?null:i);}}>Chặng {i+1} · {s.title||"Chặng mới"}</summary><div className="website-journey-fields"><div className="website-group-heading"><h3>Chặng {i+1}</h3><div className="website-inline-actions"><button type="button" className="admin-secondary" aria-label={`Đưa chặng ${i+1} lên`} disabled={i===0} onClick={()=>{const next=[...journey];[next[i-1],next[i]]=[next[i],next[i-1]];recapContent({journey:next});}}>↑</button><button type="button" className="admin-secondary" aria-label={`Đưa chặng ${i+1} xuống`} disabled={i===journey.length-1} onClick={()=>{const next=[...journey];[next[i+1],next[i]]=[next[i],next[i+1]];recapContent({journey:next});}}>↓</button><button type="button" className="admin-text-button" onClick={()=>recapContent({journey:journey.filter((_,j)=>j!==i)})}>Gỡ</button></div></div>{(['phase','title','date','description','highlight'] as const).map(k=>field(({phase:'Tên giai đoạn',title:'Tiêu đề chặng',date:'Thời gian',description:'Câu chuyện',highlight:'Điểm nhấn'})[k],s[k]??'',v=>recapContent({journey:journey.map((o,j)=>i===j?{...o,[k]:v}:o)}),k==='description',k==='phase'||k==='title'))}</div></details>)}</section></>}
    </div><aside className="website-editor-aside"><section className="website-preview"><span className="admin-kicker">Nội dung đang chỉnh</span><h2>{view==='hero'?current?.title||String(settings.heroTitle):view==='footer'?String(settings.footerQuote):view==='memories'?String(settings.memoriesTitle):current?.title||page.title}</h2><p>{view==='memories'?String(settings.memoriesDescription):current?.description||(view==='hero'?String(settings.heroDescription):page.description)}</p>{view==='recap'&&<div className="website-preview-stats">{stats.filter(s=>s.value).map((s,i)=><div key={i}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div>}<small>Bản xem nhanh nội dung. Dùng “Xem website” để xem giao diện công khai sau khi lưu.</small></section><div className="website-related"><h3>Cùng nội dung</h3>{view==='recap'?<Link href="/admin/posts" onClick={leave}>Quản lý bài viết ↗</Link>:view==='team'?<Link href="/admin/volunteers" onClick={leave}>Quản lý thẻ thành viên ↗</Link>:<Link href="/admin/website/brand" onClick={leave}>Logo & ảnh nền ↗</Link>}</div></aside></div>}
    </fieldset><div className="website-save-bar"><p role="status">{busy?'Đang xử lý…':dirty?'Có thay đổi chưa lưu':'Nội dung đã được lưu'}</p><button className="admin-primary" disabled={busy||!dirty}>{busy?'Đang lưu…':'Lưu thay đổi'}</button></div></form>
  </section>;
}
